version: "3.5"
services:
    postgres:
        image: postgres:11
        container_name: operations_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        networks:
            - operations
        volumes:
            - postgres:/data/db

networks:
    operations:
        name: operations-network
        internal: true

volumes:
    postgres:
        driver: local
