// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ranger.Services.Operations.Data;

namespace Ranger.Services.Operations.Data.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20190909132235_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("FriendlyName")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys");
                });

            modelBuilder.Entity("Ranger.Services.Operations.Data.SagaLogData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnName("data");

                    b.Property<string>("SagaId")
                        .IsRequired()
                        .HasColumnName("saga_id");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasColumnName("saga_type");

                    b.HasKey("Id")
                        .HasName("pk_saga_log_datas");

                    b.ToTable("saga_log_datas");
                });

            modelBuilder.Entity("Ranger.Services.Operations.Data.SagaState", b =>
                {
                    b.Property<string>("SagaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("saga_id");

                    b.Property<string>("Data")
                        .HasColumnName("data");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasColumnName("saga_type");

                    b.HasKey("SagaId")
                        .HasName("pk_saga_states");

                    b.ToTable("saga_states");
                });
#pragma warning restore 612, 618
        }
    }
}
